---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/kustomize
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to publish an image/artifact.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/kustomize
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag
    ref:
    - refs/heads/master
    - refs/tags/*

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to publish an image/artifact.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: build
    pull: always
    image: maiwj/dapper:windows-1809
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: docker-publish
    image: plugins/docker:windows-1809-amd64
    settings:
      build_args:
        - SERVERCORE_VERSION=1809
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/kustomize
      tag: ${DRONE_TAG}-windows-1809
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        - tag

  - name: slack_notify
    image: plugins/slack
    settings:
      template: "Build {{build.link}} failed to publish an image/artifact.\n"
      username: Drone_Publish
      webhook:
        from_secret: slack_webhook
    when:
      event:
        exclude:
          - pull_request
      instance:
        - drone-publish.rancher.io
      status:
        - failure

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: build
    pull: always
    image: maiwj/dapper:windows-1903
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: docker-publish
    image: plugins/docker:windows-1903-amd64
    settings:
      build_args:
        - SERVERCORE_VERSION=1903
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1.agent
      password:
        from_secret: docker_password
      repo: rancher/kustomize
      tag: "${DRONE_TAG}-windows-1903"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        - tag

  - name: slack_notify
    image: plugins/slack
    settings:
      template: "Build {{build.link}} failed to publish an image/artifact.\n"
      username: Drone_Publish
      webhook:
        from_secret: slack_webhook
    when:
      event:
        exclude:
          - pull_request
      instance:
        - drone-publish.rancher.io
      status:
        - failure

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: manifest

steps:
- name: push-manifest
  image: plugins/manifest:1.1.0
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    ignore_missing: true
  when:
    event:
    - tag

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to push manifests.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
      include:
      - drone-publish.rancher.io
    status:
      - failure

trigger:
  event:
    exclude:
    - promote

depends_on:
- default-linux-amd64
- default-linux-arm64
- default-windows-1809
- default-windows-1903
