---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.4.2
  commands:
    - dapper ci
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.4.2
  commands:
    - dapper ci
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

 - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: build
    pull: default
    image: maiwj/dapper:windows-1809
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request
        - tag

 - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  volumes:
    - name: docker_pipe
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: build
    pull: default
    image: maiwj/dapper:windows-1903
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request
        - tag

 - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  volumes:
    - name: docker_pipe
      path: \\\\.\\pipe\\docker_engine
