#!/bin/bash
set -e

cd $(dirname $0)/..

. ./scripts/version

mkdir -p bin

git clone -b master --single-branch http://github.com/kubernetes-sigs/kustomize ./bin/

env GOOS=windows GOARCH=amd64 go build  -o ./bin/kustomize-Windows-x86_64.exe ./bin/kustomize/
env GOOS=linux GOARCH=arm64 go build -o ./bin/kustomize-Linux-arm64 ./bin/kustomize
env GOOS=linux GOARCH=amd64 go build -o ./bin/kustomize-Linux-amd64 ./bin/kustomize

echo Built ./bin/kustomize-$(uname -s)-$(uname -m)
